server:
  port: 8761
security:
  basic:
    enabled: true
  user:
    name: admin
    password: admin123
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

