server:
  port: 9191
  context.path: /
  session:
    timeout: 100
  tomcat:
    uri-encoding: utf-8
  compression:
    enabled: true
logging:
  config: classpath:conf/logback.xml
eureka:
  client:
    service-url:
      defaultZone: http://admin:admin123@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
spring:
  application:
    name: app-user

